import turtle

turtle.bgcolor("light sky blue")
turtle.color("yellow")
turtle.speed(10)
turtle.penup()
turtle.left(180)
turtle.forward(235)
turtle.right(90)
turtle.forward(275)
turtle.pendown()
turtle.begin_fill()
turtle.circle(70)
turtle.end_fill()

ray = turtle.Turtle()
ray.color("green")
ray.speed(50)
ray.begin_fill()
ray.forward(400)
ray.right(90)
ray.forward(400)
ray.right(90)
ray.forward(800)
ray.right(90)
ray.forward(400)
ray.right(90)
ray.forward(400)
ray.end_fill()

joe = turtle.Turtle()
joe.color("brown")
joe.penup()
joe.forward(200)
joe.pendown()
joe.left(90)
joe.forward(150)


turtle.exitonclick()