import turtle

turtle.bgcolor("light sky blue")
turtle.color("yellow")
turtle.speed(11)
turtle.penup()
turtle.left(180)
turtle.forward(235)
turtle.right(90)
turtle.forward(275)
turtle.pendown()
turtle.begin_fill()
turtle.circle(70)
turtle.end_fill()

ray = turtle.Turtle()
ray.color("green")
ray.speed(50)
ray.begin_fill()
ray.forward(400)
ray.right(90)
ray.forward(400)
ray.right(90)
ray.forward(800)
ray.right(90)
ray.forward(400)
ray.right(90)
ray.forward(400)
ray.end_fill()
ray.penup()
ray.forward(300)

joe = turtle.Turtle()
joe.color("brown")
joe.speed(50)
joe.penup()
joe.begin_fill()
joe.forward(200)
joe.pendown()
joe.left(90)
joe.forward(150)
joe.right(90)
joe.forward(30)
joe.right(90)
joe.forward(150)
joe.right(90)
joe.forward(30)
joe.end_fill()

tree = turtle.Turtle()
tree.color("Lawn Green")
tree.speed(50)
tree.penup()
tree.forward(280)
tree.left(90)
tree.forward(195)
tree.pendown()
tree.begin_fill()
tree.circle(70)
tree.end_fill()

apple = turtle.Turtle()
apple.color("red")
apple.speed(11)
apple.penup()
apple.forward(190)
apple.left(90)
apple.forward(160)
apple.pendown()
apple.begin_fill()
apple.circle(8)
apple.end_fill()
apple.penup()
apple.forward(40)
apple.right(90)
apple.forward(60)
apple.pendown()
apple.begin_fill()
apple.circle(8)
apple.end_fill()
apple.penup()
apple.forward(150)

barn = turtle.Turtle()
barn.color("red")
barn.speed(11)
barn.penup()
barn.right(90)
barn.forward(100)
barn.pendown()
barn.begin_fill()
barn.right(90)
barn.forward(200)
barn.right(90)
barn.forward(200)
barn.right(90)
barn.forward(200)
barn.right(90)
barn.forward(200)
barn.end_fill()
barn.right(180)
barn.forward(200)
barn.color("white")
barn.begin_fill()
barn.left(45)
barn.forward(90)
barn.left(45)
barn.forward(73)
barn.left(45)
barn.forward(90)
barn.left(135)
barn.forward(200)
barn.end_fill()
barn.penup()
barn.right(90)
barn.forward(200)
barn.right(90)
barn.forward(100)
barn.color("black")
barn.pendown()
barn.right(90)
barn.forward(50)
barn.right(90)
barn.color("white")
barn.begin_fill()
barn.forward(50)
barn.right(90)
barn.forward(50)
barn.right(90)
barn.forward(100)
barn.right(90)
barn.forward(50)
barn.right(90)
barn.forward(50)
barn.end_fill()
barn.right(90)
barn.color("black")
barn.forward(50)
barn.penup()
barn.forward(300)
turtle.exitonclick()

